ClothBazar.Web/Controllers/ProductController.cs
using ClothBazar.Entities;
using ClothBazar.Services;
using ClothBazar.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;                                     

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        //ProductsService productsService = new ProductsService();
        //CategoriesService categoryService = new CategoriesService();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search, int ? pageNo)
        {
            var pageSize = ConfigurationsService.ClassObject.PageSize();
           
            ProductSearchViewModels models = new ProductSearchViewModels();

            models.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo.Value> 0 ? pageNo.Value :1 : 1;           //For Pagenation

            var totalRecords = ProductsService.ClassObject.GetProductsCount(search);
            models.Products = ProductsService.ClassObject.GetProducts(search, pageNo.Value,pageSize);
            models.Pager = new Pager(totalRecords, pageNo, pageSize);
            return PartialView(models);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ProductViewModels models = new ProductViewModels();
            models.AvailableCategories = CategoriesService.ClassObject.GetAllCategories();
            return PartialView(models);
        }

        [HttpPost]
        public ActionResult Create(ProductViewModels models)
        {
           
            var newProduct = new Product();
            newProduct.Name = models.Name;
            newProduct.Description = models.Description;
            newProduct.Price = models.Price;
            newProduct.ImageURL = models.ImageURL;
            newProduct.Category = CategoriesService.ClassObject.GetCategory(models.CategoryId);
            ProductsService.ClassObject.SaveProduct(newProduct);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EditProductViewModels models = new EditProductViewModels();

            var product = ProductsService.ClassObject.GetProduct(Id);
            models.Id = product.Id;
            models.Name = product.Name;
            models.Description = product.Description;
            models.Price = product.Price;
            models.CategoryId = product.Category != null ? product.Category.Id : 0;
            models.ImageURL = product.ImageURL;
            models.AvailableCategories = CategoriesService.ClassObject.GetAllCategories();

            return PartialView(models);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModels models)
        {
            var existingProduct = ProductsService.ClassObject.GetProduct(models.Id);
            existingProduct.Name = models.Name;
            existingProduct.Description = models.Description;
            existingProduct.Price = models.Price;

            existingProduct.Category = null; //make it null because the referency key is changed
            existingProduct.CategoryId = models.CategoryId;
            
           // do not update if imageUrl is empty
            if (!string.IsNullOrEmpty(models.ImageURL))
            {
                existingProduct.ImageURL = models.ImageURL;
            }
            ProductsService.ClassObject.UpdateProduct(existingProduct);


            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            ProductViewModel models = new ProductViewModel();

            models.Product = ProductsService.ClassObject.GetProduct(Id);

            return View(models);
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            ProductsService.ClassObject.DeleteProduct(Id);
            return RedirectToAction("ProductTable");
        }
    }

}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();

            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);/*file.FileName;*/
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);
                file.SaveAs(path);
                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}",fileName) };
                //var newImage = new Image() { Name = fileName };
                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, file = newImage.Id, InageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { Success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch(Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

ClothBazar.Web/Views/Product/Create.cshtml
@model  ProductViewModels
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/placeholder-image.png";
}

<div class="container">
    <h2>Create Product</h2>
    <hr />
    <form id="createProduct">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Category</label>
                    <select name="CategoryId" class="form-control">
                        @foreach (var category in Model.AvailableCategories)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input name="Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input name="Description" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Price</label>
                    <input name="Price" class="form-control" />
                </div>

                <div class="form-group">
                    <label>Image</label>
                    <input type="hidden" id="ImageURL" name="ImageURL" />
                    <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumb">
                    <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <button class="form-control btn btn-danger" type="button" id="saveBtn">Save</button>
            </div>
            <div class="col-md-4">
                <button class="form-control btn btn-danger" type="button" id="cancelBtn">Cancel</button>
            </div>
        </div>
    </form>
</div>

@*Usin Ajax to save Image*@
<script>
	$("#imageUpload").change(function () {
		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);
        	if (response.Success) {
        		$("#ImageURL").val(response.ImageURL);
        		$("#productImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
</script>

<script>
    $("#createProduct").validate({
        rules: {
            Name: {
                required: true,
                minlength: 4,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            },
            Price: {
                required: true,
                range: [1, 10000000]
            }     
        },
        messages: {
            Name: {
                required: "Name is required",
                minlength: "Minlength is 4",
                maxlength: "Maxlength is 50"
            },
            Description: {
                maxlenght: "Maxlength is 500"
            },
            Price: {
                required: "Price is Required",
                range:"Price must be with in range of 1 - 10000000"
            }
        }
    });
</script>

@*Usin Ajax to save data*@
<script>
    $("#saveBtn").click(function () {
        if ($("#createProduct").valid()) {

            $.ajax({
                type: "Post",
                url: "/Product/Create",
                data: $("#createProduct").serialize()
            })
                .done(function (resposen) {
                    $("#tableContiner").html(resposen);
                    $("#actionContainer").html("");
                    focusAction("tableContiner");
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    swal({
                        title: "Warning",
                        text: "Please enter all requred fielsd !",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                });
        }
        else {
            swal({
                title: "Warning",
                text: "Please enter all valid data in this fielsd !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }

    });
</script>

<script>
    $("#cancelBtn").click(function () {

        $("#actionContainer").html("");
        focusAction("tableContiner");
    });
</script>

ClothBazar.Web/Views/Product/Edit.cshtml
@model EditProductViewModels
@{
    ViewBag.Title = "Edit";
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";

}

<div class="container">
    <h2>Edit Product</h2>
    <hr />
    <form id="editProduct">
        <input type="hidden" name="Id" value="@Model.Id" />
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Category</label>
                    <select class="form-control" name="CategoryId">
                        @foreach (var category in Model.AvailableCategories)
                        {
                            var selected = category.Id == Model.CategoryId ? "selected" : string.Empty;
                            <option value="@category.Id" @selected> @category.Name</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" value="@Model.Name" />
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input class="form-control" name="Description" value="@Model.Description" />
                </div>
                <div class="form-group">
                    <label>Price</label>
                    <input class="form-control" name="Price" value="@Model.Price" />
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <input type="hidden" id="ImageURL" name="ImageURL" />
                    <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumb">
                    <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <button class="form-control btn btn-danger" type="button" id="updateBtn">Update</button>
            </div>
            <div class="col-md-4">
                <button class="form-control btn btn-danger" type="button" id="cancelBtn">Cancel</button>
            </div>
        </div>
    </form>
</div>


<script>
    $("#updateBtn").click(function () {
        $.ajax({
            type: "Post",
            url: "@Url.Action("Edit","Product")",//"/Product/Edit",
            data: $("#editProduct").serialize()
        })
            .done(function (resposen) {
                $("#tableContiner").html(resposen);
                $("#actionContainer").html("");
                focusAction("tableContiner");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
     $("#imageUpload").change(function () {
		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
            })
            .done(function (response) {
            console.log(response);
            if (response.Success) {
            $("#ImageURL").val(response.ImageURL);
            $("#productImage").attr("src", response.ImageURL);
            }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
            });
            });
</script>

<script>
      $("#cancelBtn").click(function () {
      $("#actionContainer").html("");
       focusAction("tableContiner");
      });
 </script>

ClothBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Products";
}
    <section class="flat-row flat-iconbox">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-section">
                        <h2 class="title">Products</h2>
                    </div>
                </div>
            </div>
        <div id="tableContiner">
            @{
                Html.RenderAction("ProductTable");
            }
        </div>

        <hr />
        <div id="actionContainer">
            </div>
        </div>
    </section>

<script>
	function focusAction(controlToFocus) {
		$('html, body').animate({
			scrollTop: $("#" + controlToFocus).offset().top - 100
		}, 1000);
	}
    </script>
    
       

ClothBazar.Web/Views/Product/ProductTable.cshtml
@model ProductSearchViewModels
@{
    ViewBag.Title = "ProductTable";
}

<div class="form-control">
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" name="search" id="searchTxt" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4">
                            <button class="form-control btn btn-danger" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4">
                            <button class="form-control btn btn-danger" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4">
                            <button class="form-control btn btn-danger" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="form-control">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th class="font-weight-bold">Product Name</th>
                <th class="font-weight-bold">Category</th>
                <th class="font-weight-bold"> Price</th>
                <th class="font-weight-bold wrap-td">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@product.Id"> Edit </button>
                            <button class="deleteBtn" data-id="@product.Id">Delete</button>
                            <button class="addtocart" data-id="@product.Id">Add To Cart</button>
                        </td>
                    </tr>
                }

            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products Found.</td>
                </tr>
            }
        </tbody>
    </table>

    <div>
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {
            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageNo="1">First</button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage-1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageNo="@page"> @page </button>
            }
            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage+1)">Next</button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.EndPage)">Last</button>
            }
        }
    </div>

</div>

<script>
    $(".pageButtons").click(function () {
        $.ajax({
            url: "@Url.Action("ProductTable", "Product")",//"/Product/ProductTable",
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: "@Model.SearchTerm"
            }
        })
            .done(function (resposen) {
                $("#tableContiner").html(resposen);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();

        $.ajax({
            type: "Get",
            url: "@Url.Action("ProductTable", "Product")",//"/Product/ProductTable",
            data: {
                search: searchValue
            }
        })
            .done(function (resposen) {
                $("#tableContiner").html(resposen);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $("#resetBtn").click(function () {
        var searchValue = "";

        $.ajax({
            type: "Get",
            url: "@Url.Action("ProductTable", "Product")",//"/Product/ProductTable",
            data: {
                search: searchValue
            }
        })
            .done(function (resposen) {
                $("#tableContiner").html(resposen);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $("#newBtn").click(function () {
        $.ajax({
            type: "Get",
            url: "@Url.Action("Create", "Product")",//"/Product/Create",
        })
            .done(function (resposen) {
                $("#actionContainer").html(resposen);

                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $(".editBtn").click(function () {
        $.ajax({
            type: "Get",
            url: "@Url.Action("Edit", "Product")",//"/Product/Edit",
            data: {
                Id: $(this).attr("data-id")
            }

        })
            .done(function (resposen) {
                $("#actionContainer").html(resposen);
                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $(".deleteBtn").click(function () {

        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this imaginary file!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {

                    $.ajax({
                        type: "Post",
                        url: "@Url.Action("Delete", "Product")",//"/Product/Delete",
                        data: {
                            Id: $(this).attr("data-id")
                        }
                    })
                        .done(function (resposen) {
                            $("#tableContiner").html(resposen);

                            swal("Record Delete Successfully!", {
                                icon: "success",
                            });
                        })
                        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("Fail");
                        });
                }

            });
        //var confirmDelete = confirm("Are Want Delete This Product?")
        //if (confirmDelete)
        //{
        //    $.ajax({
        //        type: "Post",
        //        url: "/Product/Delete",
        //        data: {
        //            Id: $(this).attr("data-id")
        //        }
        //    })
        //        .done(function (resposen) {
        //            $("#tableContiner").html(resposen);
        //        })
        //        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        //            alert("Fail");
        //        });
        //}

    });

    var products = [];
    $(".addtocart").click(function () {
        var productId = $(this).attr("data-id");
        products.push(productId);
        $.cookie("CartProducts", products.join("-"), { path: "/" });
        alert("Product added to cart");
    });

</script>