ClothBazar.Web/Controllers/CategoryController.cs
 using ClothBazar.Entities;
using ClothBazar.Services;
using ClothBazar.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class CategoryController : Controller
    {
        //CategoriesService categoriesService = new CategoriesService();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryTable(string search , int? pageNo)
        {
            var pageSize = ConfigurationsService.ClassObject.PageSize();
            CategorySearchViewModels models = new CategorySearchViewModels();

            models.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoriesService.ClassObject.GetCategoriesCount(search);
            models.Categories = CategoriesService.ClassObject.GetCategories(search,pageNo.Value,pageSize);

            if (models.Categories != null)
            {
                models.Pager = new Pager(totalRecords, pageNo, pageSize);
                return PartialView("CategoryTable", models);
            }
            else
            {
                return HttpNotFound();
            }
        }
        // GET: Category
        [HttpGet]
        public ActionResult Create()
        {
            CategoryViewModels models = new CategoryViewModels();

            return PartialView(models);
        }
        [HttpPost]
        public ActionResult Create(CategoryViewModels models)
        {
            if(ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = models.Name;
                newCategory.Description = models.Description;
                newCategory.ImageURL = models.ImageURL;
                newCategory.isFeatured = models.isFeatured;

                CategoriesService.ClassObject.SaveCategory(newCategory);

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EditCategoryViewModels models = new EditCategoryViewModels();
            var category = CategoriesService.ClassObject.GetCategory(Id);
            models.Id = category.Id;
            models.Name = category.Name;
            models.Description = category.Description;
            models.ImageURL = category.ImageURL;
            models.isFeatured = category.isFeatured;

            return PartialView(models);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModels models)
        {
            var existingCategory = CategoriesService.ClassObject.GetCategory(models.Id);
            existingCategory.Name = models.Name;
            existingCategory.Description = models.Description;
            existingCategory.ImageURL = models.ImageURL;
            existingCategory.isFeatured = models.isFeatured;
            CategoriesService.ClassObject.UpdateCategory(existingCategory);
            return RedirectToAction("CategoryTable");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            CategoriesService.ClassObject.DeleteCategory(Id);

            return RedirectToAction("CategoryTable");
        }

    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();

            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);/*file.FileName;*/
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);
                file.SaveAs(path);
                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}",fileName) };
                //var newImage = new Image() { Name = fileName };
                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, file = newImage.Id, InageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { Success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch(Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

ClothBazar.Web/Views/Category/CategoryTable.cshtml
@model ClothBazar.Web.ViewModel.CategorySearchViewModels

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-danger form-control" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4">
                            <button class="form-control btn btn-danger" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-danger form-control" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="form-control">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th class="font-weight-bold">Category Name</th>
                <th class="font-weight-bold">Products</th>
                <th class="font-weight-bold wrap-td">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td>@category.Name</td>
                        <td>
                            @category.Products.Count
                            <br />
                            @foreach (var product in category.Products)
                            {
                                <span>@product.Name, </span>
                            }
                        </td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@category.Id">Edit</button>
                            <button class="deleteBtn" data-id="@category.Id">Delete</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="3" class="text-danger">No Categories found.</td></tr>
            }
        </tbody>
    </table>

    <div>
        @if (Model.Pager != null && Model.Pager.TotalPages>1)
        {
            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageNo="1">First</button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage-1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageNo="@page"> @page </button>
            }
            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage+1)">Next</button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.EndPage)">Last</button>
            }
        }
    </div>

</div>

<script>
    $(".pageButtons").click(function () {
        $.ajax({
            url: "@Url.Action("CategoryTable", "Category")",//"/Category/ProductTable",
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: "@Model.SearchTerm"
            }
        })
            .done(function (resposen) {
                $("#tableContiner").html(resposen);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $("#resetBtn").click(function () {
        var searchValue = "";

        $.ajax({
            type: "Get",
            url: "@Url.Action("CategoryTable", "Category")",//"/Category/CategoryTable",
            data: {
                search: searchValue
            }
        })
            .done(function (resposen) {
                $("#tableContiner").html(resposen);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();

        $.ajax({
            url:" @Url.Action("CategoryTable","Category")",  /*'/Category/CategoryTable'*/
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContiner").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script>

<script>
        $("#newBtn").click(function () {
        $.ajax({
            url:"@Url.Action("Create","Category")", //'/Category/Create',
        })
            .done(function (response) {
                $("#actionContainer").html(response);

                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script>

<script>
        $(".editBtn").click(function () {
        $.ajax({
            url: "@Url.Action("Edit","Category")", //'/Category/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script>

<script>
     $(".deleteBtn").click(function () {

        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this imaginary file!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {

                    $.ajax({
                        type: "Post",
                        url: "@Url.Action("Delete", "Category")",//"/Category/Delete",
                        data: {
                            Id: $(this).attr("data-id")
                        }
                    })
                        .done(function (resposen) {
                            $("#tableContiner").html(resposen);

                            swal("Record Delete Successfully!", {
                                icon: "success",
                            });
                        })
                        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("Fail");
                        });
                }

            });

        @*var confirmDelete = confirm("Are you sure you want to delete this category?");

        if (confirmDelete) {
            $.ajax({
                type: 'POST',
                url: "@Url.Action("Delete","Category")",//'/Category/Delete',
                data: {
                    ID: $(this).attr('data-id')
                }
            })
                .done(function (response) {
                    $("#tableContiner").html(response);
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });
        }*@
    });

</script> 

ClothBazar.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/placeholder-image.png";
}

    <div class="container">

        <h2>Create</h2>
        <hr />
        <form id="createCategory">
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label>Name<span class="text-danger">*</span></label>
                        <input class="form-control" name="Name" />
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <input class="form-control" name="Description" />
                    </div>
                    <div class="form-group">
                        <label> Image</label>
                        <input id="ImageURL" name="ImageURL" type="hidden" />
                        <input class="form-control" id="imageUplode" name="image" type="file" accept=" .png , .jpg" />
                    </div>
                    <div class="form-group">
                        <label>Is Featured ?</label>
                        <div class="input-group">
                            <div class="radio form-control">
                                <label>
                                    <input type="radio" name="isFeatured" value="True" />True
                                </label>
                            </div>
                            <div class="radio form-control">
                                <label>
                                    <input type="radio" name="isFeatured" value="False" />False
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="thumb">
                        <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <button class="form-control btn btn-danger" type="button" id="saveBtn">Save</button>
                </div>
                <div class="col-md-4">
                    <button class="form-control btn btn-danger" type="button" id="cancelBtn">Cancel</button>
                </div>
            </div>

        </form>
    </div>


@*uplode Mulitiple/Single Image*@
<script>
    $("#imageUplode").change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: "Post",
            url: "@Url.Action("UploadImage", "Shared")", //"/Shared/UploadImage",
            data: formData,
            dataType: "Json",
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);
                if (response.Success == true) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .file(function (XMLHttpRequest, textStatus, erroThrown) {
                alert("Fail");
            });
    });
</script>

<script>
    $("#createCategory").validate({
        rules: {
            Name: {
                required: true,
                minlength: 4,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            Name: {
                required: "Name is required",
                minlength: "Minlength is 4",
                maxlength:"Maxlength is 50"
            },
            Description: {
                maxlenght:"Maxlength is 500"
            }
        }
    });
</script>

<script>
    $("#saveBtn").click(function () {
        if ($("#createCategory").valid()) {
            $.ajax({
                type: 'POST',
                url: "@Url.Action("Create", "Category")", //'/Category/Create',
                data: $("#createCategory").serialize()
            })
                .done(function (response) {
                    $("#tableContiner").html(response);
                    $("#actionContainer").html("");
                    focusAction("tableContiner");
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    swal({
                        title: "Warning",
                        text: "Please enter all requred fielsd !",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                });
        }
        else {
            swal({
                title: " JS Warning",
                text: "Please enter all valid data in this fielsd !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }
    });
</script>

<script>
    $("#cancelBtn").click(function () {

        $("#actionContainer").html("");
        focusAction("tableContiner");
    });
</script>

ClothBazar.Web/Views/Category/Edit.cshtml
@model  EditCategoryViewModels
@{
    ViewBag.Title = "Edit";
    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";
}

<div class="container">
    <h2>Edit</h2>
    <hr />
    <form id="editCategory">

        <input type="hidden" name="Id" value="@Model.Id" />
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" value="@Model.Name" />
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input class="form-control" name="Description" value="@Model.Description" />
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <input type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
                    <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
                </div>
                <div class="form-group">
                    <label>Is Featured?</label>
                    <div class="input-group">
                        <div class="radio form-control">
                            <label><input name="isFeatured" type="radio" value="True" @trueChecked /> True</label>
                        </div>
                        <div class="radio form-control">
                            <label><input name="isFeatured" type="radio" value="False" @falseChecked /> False</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumb">
                    <img src="@imageURL" class="img-thumbnail img-fluid" id="categoryImage" />
                </div>
            </div>
        </div>
          <div class="row">
              <div class="col-md-4"> 
                  <button id="updateBtn" class="form-control btn btn-danger" type="button">Update</button>
              </div>
               <div class="col-md-4">
                   <button id="cancelBtn" class="form-control btn btn-danger" type="button">Cancel</button
               </div>
          </div>
    </form>
</div>

<script>
    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: "@Url.Action("UploadImage", "Shared")",//'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);
                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    $("#updateBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: "@Url.Action("Edit", "Category")",//'/Category/Edit',
            data: $("#editCategory").serialize()
        })
            .done(function (response) {
                $("#tableContiner").html(response);
                $("#actionContainer").html("");
                focusAction("tableContiner");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script> 

<script>
    $("#cancelBtn").click(function () {

        $("#actionContainer").html("");
        focusAction("tableContiner");
    });

</script>

ClothBazar.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Categories";
}
<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Categories
                    </h2>
                </div>
            </div>
        </div>
        <div id="tableContiner">
            @{
                Html.RenderAction("CategoryTable");
            }
        </div>

        <hr />
        <div id="actionContainer">

        </div>
    </div>
</section>
<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>